<?php

namespace App\Console\Commands;

use App\Catalog\CompiledCatalog;
use App\Catalog\Hosts;
use App\Routing\IriCanonicalizer;
use App\Routing\LinkProjector;
use App\Routing\PublicSuffixList;
use App\Routing\Rulepack;
use Illuminate\Console\Command;

/**
 * Generates the positive half of the routing corpus BY WALKING the compiled
 * detectors, so it cannot silently miss one — the failure mode a hand-written
 * corpus has. For each detector it synthesises a URL its own pattern accepts,
 * runs the real canonicaliser + projector, and keeps the case only if the
 * round trip lands on that detector's surface with the expected capture.
 *
 * Detectors it cannot satisfy are reported, never skipped silently: an
 * unsatisfiable pattern is a catalog bug worth seeing.
 */
class RoutingCorpusCommand extends Command
{
    protected $signature = 'routing:corpus
        {--out= : where to write (default tests/Fixtures/Routing/corpus-generated.php)}
        {--check : verify the committed corpus still round-trips; write nothing}';

    protected $description = 'Generate/verify the detector-derived half of the routing corpus';

    public function handle(): int
    {
        $canonicalizer = new IriCanonicalizer(PublicSuffixList::instance());
        $projector = new LinkProjector(Rulepack::fromCompiledCatalog());

        $cases = [];
        $unsatisfiable = [];

        foreach (CompiledCatalog::detectors() as $id => $detector) {
            if ($detector['surface_key'] === null) {
                continue; // pure signal — never places, nothing to assert
            }

            $url = $this->synthesize($detector);
            if ($url === null) {
                $unsatisfiable[$id] = 'could not synthesise a URL for this pattern';

                continue;
            }

            $projection = $projector->project($canonicalizer->canonicalize($url));

            if (! $projection->matched() || $projection->surfaceKey !== $detector['surface_key']) {
                $unsatisfiable[$id] = sprintf(
                    'synthesised %s → %s (expected %s)',
                    $url,
                    $projection->matched() ? $projection->surfaceKey : 'no match ('.$projection->reason.')',
                    $detector['surface_key'],
                );

                continue;
            }

            $cases[] = [
                'url' => $url,
                'expect' => array_filter([
                    'surface' => $projection->surfaceKey,
                    'identifier' => $projection->identifier,
                ], fn ($v) => $v !== null),
                'detector' => $id,
            ];
        }

        usort($cases, fn (array $a, array $b) => strcmp($a['url'], $b['url']));

        $path = $this->option('out') ?: base_path('tests/Fixtures/Routing/corpus-generated.php');

        if ($this->option('check')) {
            if (! is_file($path)) {
                $this->error('No generated corpus committed.');

                return self::FAILURE;
            }
            $committed = require $path;
            if (count($committed) !== count($cases)) {
                $this->error(sprintf('Corpus is stale: committed %d cases, definitions now produce %d. Run `php artisan routing:corpus`.', count($committed), count($cases)));

                return self::FAILURE;
            }
        }

        $this->report($cases, $unsatisfiable);

        if (! $this->option('check')) {
            if (! is_dir(dirname($path))) {
                mkdir(dirname($path), 0755, true);
            }
            $body = "<?php\n\n// GENERATED by `php artisan routing:corpus` — do not edit by hand.\n"
                ."// One case per catalog detector that can place a surface: a URL its own\n"
                ."// pattern accepts, plus the surface and identifier the real pipeline\n"
                ."// produced for it. Hand-written attacker/negative cases live alongside\n"
                ."// this file in corpus-negatives.php.\nreturn ".var_export($cases, true).";\n";
            file_put_contents($path, $body);
            $this->info('Wrote '.count($cases).' cases to '.$path);
        }

        return $unsatisfiable === [] ? self::SUCCESS : self::FAILURE;
    }

    /** @param array<string, array<string, mixed>> $cases */
    private function report(array $cases, array $unsatisfiable): void
    {
        $this->info(sprintf('%d detector(s) round-tripped.', count($cases)));

        if ($unsatisfiable !== []) {
            $this->error(count($unsatisfiable).' detector(s) could not be exercised:');
            foreach ($unsatisfiable as $id => $why) {
                $this->line("  {$id}: {$why}");
            }
        }
    }

    /**
     * Build a URL the detector's own rules accept: host from the registrable
     * key (plus a subdomain the pattern likes), a path built by filling the
     * pattern's literal segments and capture groups, and any required query
     * params.
     *
     * @param  array<string, mixed>  $detector
     */
    private function synthesize(array $detector): ?string
    {
        $host = $detector['registrable_key'];
        if ($host === null) {
            return null;
        }

        if ($detector['subdomain_pattern'] !== null) {
            $sub = $this->sampleFor($detector['subdomain_pattern']);
            if ($sub === null) {
                return null;
            }
            $host = $sub.'.'.$host;
        } elseif (in_array($host, Hosts::suffixOverrides(), true)) {
            // A multi-tenant suffix is itself a public suffix — no real URL
            // ever has the bare host, so the sample needs a tenant label.
            $host = 'acmestore.'.$host;
        }

        $path = '/';
        if ($detector['path_pattern'] !== null) {
            $path = $this->samplePath($detector['path_pattern']);
            if ($path === null) {
                return null;
            }
        }

        $url = 'https://'.$host.$path;

        if ($detector['query_requires'] !== []) {
            $params = [];
            foreach ($detector['query_requires'] as $i => $param) {
                $params[$param] = 100000 + $i;
            }
            $url .= '?'.http_build_query($params);
        }

        return $url;
    }

    /**
     * Turn a path regex into a matching path. Handles the shapes this catalog
     * actually uses: anchored literals, alternation groups, named captures
     * with a charset+quantifier, optional groups, and negative lookaheads
     * (which are simply avoided by choosing a capture value that cannot
     * collide with the reserved words they list).
     */
    private function samplePath(string $pattern): ?string
    {
        $sample = $this->sampleFragment($pattern);
        if ($sample === null) {
            return null;
        }
        $sample = str_replace('//', '/', $sample);

        return str_starts_with($sample, '/') ? $sample : '/'.$sample;
    }

    /**
     * Sample a pattern WITHOUT forcing a leading slash — what group bodies and
     * subdomain patterns need. (Forcing one here is what produced `/@/aaa`
     * from `/@(?<handle>…)`: the group's own sample gained a slash.)
     */
    private function sampleFragment(string $pattern): ?string
    {
        $body = $this->patternBody($pattern);
        if ($body === null) {
            return null;
        }

        $out = '';
        $i = 0;
        $len = strlen($body);

        while ($i < $len) {
            $c = $body[$i];

            if ($c === '^' || $c === '$') {
                $i++;

                continue;
            }

            if ($c === '\\' && $i + 1 < $len) {
                $next = $body[$i + 1];
                // \d etc. as a bare token (rare here, but cheap to support)
                $out .= match ($next) {
                    'd' => '1',
                    'w' => 'a',
                    default => $next,
                };
                $i += 2;
                // consume a quantifier on the escape
                $i = $this->skipQuantifier($body, $i);

                continue;
            }

            if ($c === '(') {
                $group = $this->readGroup($body, $i);
                if ($group === null) {
                    return null;
                }
                [$inner, $after, $isLookahead] = $group;
                if ($isLookahead) {
                    $i = $after;

                    continue;
                }
                $sample = $this->sampleGroup($inner);
                if ($sample === null) {
                    return null;
                }
                // An optional group ((...)? ) can simply be omitted, which is
                // the safest choice: fewer segments, fewer ways to trip a
                // reject pattern.
                if ($after < $len && ($body[$after] === '?' || $body[$after] === '*')) {
                    $i = $after + 1;

                    continue;
                }
                $out .= $sample;
                $i = $this->skipQuantifier($body, $after);

                continue;
            }

            if ($c === '[') {
                $close = $this->matchingBracket($body, $i);
                if ($close === null) {
                    return null;
                }
                $class = substr($body, $i + 1, $close - $i - 1);
                $quantEnd = $this->skipQuantifier($body, $close + 1);
                $reps = $this->minRepetitions($body, $close + 1);
                $out .= str_repeat($this->sampleClass($class), max(1, $reps));
                $i = $quantEnd;

                continue;
            }

            // Literal — but an OPTIONAL literal (`@?`) is omitted rather than
            // emitted, or the sample contains a stray '?' that no pattern
            // accepts.
            $next = $body[$i + 1] ?? '';
            if (in_array($next, ['?', '*'], true)) {
                $i = $this->skipQuantifier($body, $i + 1);

                continue;
            }
            $out .= $c;
            $i++;
            $i = $this->skipQuantifier($body, $i);
        }

        return $out;
    }

    private function sampleFor(string $pattern): ?string
    {
        $sample = $this->sampleFragment($pattern);

        return $sample === null ? null : trim($sample, '/');
    }

    /** @return array{0: string, 1: int, 2: bool}|null [inner, indexAfterGroup, isLookahead] */
    private function readGroup(string $body, int $start): ?array
    {
        $depth = 0;
        for ($i = $start; $i < strlen($body); $i++) {
            if ($body[$i] === '\\') {
                $i++;

                continue;
            }
            if ($body[$i] === '(') {
                $depth++;
            }
            if ($body[$i] === ')') {
                $depth--;
                if ($depth === 0) {
                    $inner = substr($body, $start + 1, $i - $start - 1);
                    $isLookahead = str_starts_with($inner, '?!') || str_starts_with($inner, '?=');

                    return [$inner, $i + 1, $isLookahead];
                }
            }
        }

        return null;
    }

    private function sampleGroup(string $inner): ?string
    {
        // Strip group prefixes: ?: non-capturing, ?<name> named.
        $inner = preg_replace('/^\?:/', '', $inner) ?? $inner;
        $inner = preg_replace('/^\?P?<[A-Za-z_][A-Za-z0-9_]*>/', '', $inner) ?? $inner;

        // Alternation: take the first branch at depth 0.
        $depth = 0;
        for ($i = 0; $i < strlen($inner); $i++) {
            $ch = $inner[$i];
            if ($ch === '\\') {
                $i++;

                continue;
            }
            if ($ch === '(') {
                $depth++;
            }
            if ($ch === ')') {
                $depth--;
            }
            if ($ch === '|' && $depth === 0) {
                $inner = substr($inner, 0, $i);
                break;
            }
        }

        return $this->sampleFragment('#'.$inner.'#');
    }

    private function sampleClass(string $class): string
    {
        // Deliberate preference order: a letter reads like a real handle and
        // is accepted by every charset these patterns use; digits next for
        // numeric-id rules.
        foreach (['a', 'b', 'x', '1', '2', '-', '_', '.'] as $candidate) {
            if (@preg_match('/^['.$class.']$/', $candidate) === 1) {
                return $candidate;
            }
        }

        return 'a';
    }

    private function minRepetitions(string $body, int $at): int
    {
        if ($at >= strlen($body)) {
            return 1;
        }
        if ($body[$at] === '+') {
            return 3;
        }
        if ($body[$at] === '*') {
            return 3;
        }
        if ($body[$at] === '{' && preg_match('/^\{(\d+)/', substr($body, $at), $m)) {
            return max(1, (int) $m[1]);
        }

        return 1;
    }

    private function skipQuantifier(string $body, int $at): int
    {
        if ($at >= strlen($body)) {
            return $at;
        }
        if (in_array($body[$at], ['+', '*', '?'], true)) {
            $at++;
        } elseif ($body[$at] === '{') {
            $close = strpos($body, '}', $at);
            if ($close !== false) {
                $at = $close + 1;
            }
        }
        // lazy/possessive modifier
        if ($at < strlen($body) && in_array($body[$at], ['?', '+'], true)) {
            $at++;
        }

        return $at;
    }

    private function matchingBracket(string $body, int $start): ?int
    {
        for ($i = $start + 1; $i < strlen($body); $i++) {
            if ($body[$i] === '\\') {
                $i++;

                continue;
            }
            if ($body[$i] === ']' && $i > $start + 1) {
                return $i;
            }
        }

        return null;
    }

    /** Strip the delimiters and trailing modifiers from a PCRE pattern. */
    private function patternBody(string $pattern): ?string
    {
        if (strlen($pattern) < 2) {
            return null;
        }
        $delim = $pattern[0];
        $closing = match ($delim) {
            '(' => ')', '{' => '}', '[' => ']', '<' => '>',
            default => $delim,
        };
        $end = strrpos($pattern, $closing);
        if ($end === false || $end === 0) {
            return null;
        }

        return substr($pattern, 1, $end - 1);
    }
}
