<?php

// GENERATED by `php artisan routing:corpus` — do not edit by hand.
// One case per catalog detector that can place a surface: a URL its own
// pattern accepts, plus the surface and identifier the real pipeline
// produced for it. Hand-written attacker/negative cases live alongside
// this file in corpus-negatives.php.
return [
    0 => [
        'url' => 'https://aa.bigcartel.com/',
        'expect' => [
            'surface' => 'bigcartel.store',
            'identifier' => 'aa',
        ],
        'detector' => '9f849d66cd3cfcc7',
    ],
    1 => [
        'url' => 'https://aa.gumroad.com/',
        'expect' => [
            'surface' => 'gumroad.store',
            'identifier' => 'aa',
        ],
        'detector' => 'bf6cb5dce35fa7ea',
    ],
    2 => [
        'url' => 'https://aa.myshopify.com/',
        'expect' => [
            'surface' => 'shopify.store',
            'identifier' => 'aa',
        ],
        'detector' => '76a9ccd9a8e7c53a',
    ],
    3 => [
        'url' => 'https://aa.substack.com/',
        'expect' => [
            'surface' => 'substack.publication',
            'identifier' => 'aa',
        ],
        'detector' => '3beaebd9e5c3d8b1',
    ],
    4 => [
        'url' => 'https://aaa.circle.so/',
        'expect' => [
            'surface' => 'circle.community',
            'identifier' => 'aaa',
        ],
        'detector' => '94017fcb04da7092',
    ],
    5 => [
        'url' => 'https://aaa.mykajabi.com/',
        'expect' => [
            'surface' => 'kajabi.courses',
            'identifier' => 'aaa',
        ],
        'detector' => '9a888e4bc937d7e5',
    ],
    6 => [
        'url' => 'https://aaa.resdiary.com/',
        'expect' => [
            'surface' => 'resdiary.reserve',
            'identifier' => 'aaa',
        ],
        'detector' => '82d5bfefb57c17e1',
    ],
    7 => [
        'url' => 'https://aaaa.bandcamp.com/',
        'expect' => [
            'surface' => 'bandcamp.artist',
            'identifier' => 'aaaa',
        ],
        'detector' => 'eab45cdae72b22c4',
    ],
    8 => [
        'url' => 'https://abacus.co/',
        'expect' => [
            'surface' => 'abacus.order',
        ],
        'detector' => '5eea26da85fc2399',
    ],
    9 => [
        'url' => 'https://acmestore.as.me/',
        'expect' => [
            'surface' => 'acuity.book',
        ],
        'detector' => 'e3d1269985f44b74',
    ],
    10 => [
        'url' => 'https://acmestore.gettimely.com/',
        'expect' => [
            'surface' => 'timely.book',
        ],
        'detector' => 'f521d831f543093a',
    ],
    11 => [
        'url' => 'https://acmestore.nowbookit.com/?accountid=100000&venueid=100001',
        'expect' => [
            'surface' => 'nowbookit.reserve',
        ],
        'detector' => '61b7c316fdcaa81d',
    ],
    12 => [
        'url' => 'https://acmestore.setmore.com/',
        'expect' => [
            'surface' => 'setmore.book',
        ],
        'detector' => 'cb254f601df38e09',
    ],
    13 => [
        'url' => 'https://acmestore.simplybook.me/',
        'expect' => [
            'surface' => 'simplybook_me.book',
        ],
        'detector' => 'a102b1090efe3444',
    ],
    14 => [
        'url' => 'https://acmestore.square.site/',
        'expect' => [
            'surface' => 'square.book',
        ],
        'detector' => '4a177e0bdd28c67f',
    ],
    15 => [
        'url' => 'https://acmestore.square.site/s/order/',
        'expect' => [
            'surface' => 'square.order',
        ],
        'detector' => '9050e12b984132ba',
    ],
    16 => [
        'url' => 'https://acmestore.youcanbook.me/',
        'expect' => [
            'surface' => 'youcanbookme.book',
        ],
        'detector' => '9e6abeeb345bb38c',
    ],
    17 => [
        'url' => 'https://acuityscheduling.com/',
        'expect' => [
            'surface' => 'acuity.book',
        ],
        'detector' => '7c8853389c4e92a1',
    ],
    18 => [
        'url' => 'https://admitone.com/',
        'expect' => [
            'surface' => 'admitone.tickets',
        ],
        'detector' => '1208c937fd429faf',
    ],
    19 => [
        'url' => 'https://admitonelive.com/',
        'expect' => [
            'surface' => 'admitone.tickets',
        ],
        'detector' => '7033a9351e28cde9',
    ],
    20 => [
        'url' => 'https://app.google/',
        'expect' => [
            'surface' => 'google_appointments.book',
        ],
        'detector' => '5644cedd176de3b3',
    ],
    21 => [
        'url' => 'https://audiomack.com/aa',
        'expect' => [
            'surface' => 'audiomack.artist',
            'identifier' => 'aa',
        ],
        'detector' => 'a6220fc75e15b1bc',
    ],
    22 => [
        'url' => 'https://bandsintown.com/a/1',
        'expect' => [
            'surface' => 'bandsintown.artist',
            'identifier' => '1',
        ],
        'detector' => '54d143c662208cab',
    ],
    23 => [
        'url' => 'https://bark.com/en/aa/company/aaa',
        'expect' => [
            'surface' => 'bark.company',
            'identifier' => 'aaa',
        ],
        'detector' => '092a1463f2bd7e57',
    ],
    24 => [
        'url' => 'https://beatport.com/artist/aaa/1',
        'expect' => [
            'surface' => 'beatport.artist',
            'identifier' => '1',
        ],
        'detector' => 'a2e82df0265c1cf2',
    ],
    25 => [
        'url' => 'https://behance.net/',
        'expect' => [
            'surface' => 'behance.profile',
        ],
        'detector' => 'd74e4646da084b67',
    ],
    26 => [
        'url' => 'https://behance.net/aa',
        'expect' => [
            'surface' => 'behance.profile',
            'identifier' => 'aa',
        ],
        'detector' => '8081071a53da2f5c',
    ],
    27 => [
        'url' => 'https://bellabooking.com/',
        'expect' => [
            'surface' => 'bella_booking.book',
        ],
        'detector' => '0ec0dc6194b16602',
    ],
    28 => [
        'url' => 'https://book.app/',
        'expect' => [
            'surface' => 'ovatu.book',
        ],
        'detector' => '49b8699165aa79db',
    ],
    29 => [
        'url' => 'https://booksy.com/',
        'expect' => [
            'surface' => 'booksy.book',
        ],
        'detector' => '86bb8fa004146298',
    ],
    30 => [
        'url' => 'https://bookwell.com.au/',
        'expect' => [
            'surface' => 'bookwell.book',
        ],
        'detector' => 'f48edcc99323a839',
    ],
    31 => [
        'url' => 'https://bopple.app/',
        'expect' => [
            'surface' => 'bopple.order',
        ],
        'detector' => 'd28d552aaa1cf946',
    ],
    32 => [
        'url' => 'https://bopple.com/',
        'expect' => [
            'surface' => 'bopple.order',
        ],
        'detector' => '4e3ca5bb3000384e',
    ],
    33 => [
        'url' => 'https://bopple.me/',
        'expect' => [
            'surface' => 'bopple.order',
        ],
        'detector' => '3caa16e5cecbe1c3',
    ],
    34 => [
        'url' => 'https://boulevard.io/',
        'expect' => [
            'surface' => 'boulevard.book',
        ],
        'detector' => '1444b9094dbe290e',
    ],
    35 => [
        'url' => 'https://bsky.app/profile/a',
        'expect' => [
            'surface' => 'bluesky.profile',
            'identifier' => 'a',
        ],
        'detector' => '91ad4e2a04b4d1b4',
    ],
    36 => [
        'url' => 'https://buy.stripe.com/aaaaaaaa',
        'expect' => [
            'surface' => 'stripe.payment_link',
        ],
        'detector' => 'abdf126c7c3f9024',
    ],
    37 => [
        'url' => 'https://buymeacoffee.com/',
        'expect' => [
            'surface' => 'buymeacoffee.page',
        ],
        'detector' => 'f60f728146b1ba98',
    ],
    38 => [
        'url' => 'https://buymeacoffee.com/aa',
        'expect' => [
            'surface' => 'buymeacoffee.page',
            'identifier' => 'aa',
        ],
        'detector' => '9583ecab2b38c9bf',
    ],
    39 => [
        'url' => 'https://cal.com/aa',
        'expect' => [
            'surface' => 'cal_com.book',
            'identifier' => 'aa',
        ],
        'detector' => '4b133d61c8ba4884',
    ],
    40 => [
        'url' => 'https://calendly.com/aa',
        'expect' => [
            'surface' => 'calendly.book',
            'identifier' => 'aa',
        ],
        'detector' => '0f419bcb5f7a6d86',
    ],
    41 => [
        'url' => 'https://cameo.com/aa',
        'expect' => [
            'surface' => 'cameo.profile',
            'identifier' => 'aa',
        ],
        'detector' => 'f29abc5d11e9b2a6',
    ],
    42 => [
        'url' => 'https://cash.app/$a',
        'expect' => [
            'surface' => 'cash_app.profile',
            'identifier' => 'a',
        ],
        'detector' => 'cca6b267125aa403',
    ],
    43 => [
        'url' => 'https://chope.co/',
        'expect' => [
            'surface' => 'chope.reserve',
        ],
        'detector' => 'f6c548a1dd086076',
    ],
    44 => [
        'url' => 'https://chownow.com/',
        'expect' => [
            'surface' => 'chownow.order',
        ],
        'detector' => '974d921f573a3c00',
    ],
    45 => [
        'url' => 'https://classpass.com/studios/aaa',
        'expect' => [
            'surface' => 'classpass.book',
            'identifier' => 'aaa',
        ],
        'detector' => '4231517e774169bb',
    ],
    46 => [
        'url' => 'https://cliniko.com/',
        'expect' => [
            'surface' => 'cliniko.book',
        ],
        'detector' => 'd39bf87ebb18a29e',
    ],
    47 => [
        'url' => 'https://codepen.io/',
        'expect' => [
            'surface' => 'codepen.profile',
        ],
        'detector' => '0d7e3d213bbccec3',
    ],
    48 => [
        'url' => 'https://codepen.io/aa',
        'expect' => [
            'surface' => 'codepen.profile',
            'identifier' => 'aa',
        ],
        'detector' => '851d4090d83d957f',
    ],
    49 => [
        'url' => 'https://dailymotion.com/aa',
        'expect' => [
            'surface' => 'dailymotion.channel',
            'identifier' => 'aa',
        ],
        'detector' => '1f802cb87a6b995e',
    ],
    50 => [
        'url' => 'https://deezer.com/artist/1',
        'expect' => [
            'surface' => 'deezer.artist',
            'identifier' => '1',
        ],
        'detector' => 'b8cbb2a0298bef31',
    ],
    51 => [
        'url' => 'https://deliveroo.ae/',
        'expect' => [
            'surface' => 'deliveroo.order',
        ],
        'detector' => 'ebb60595a01863b9',
    ],
    52 => [
        'url' => 'https://deliveroo.be/',
        'expect' => [
            'surface' => 'deliveroo.order',
        ],
        'detector' => '70263737f68dc13f',
    ],
    53 => [
        'url' => 'https://deliveroo.co.uk/',
        'expect' => [
            'surface' => 'deliveroo.order',
        ],
        'detector' => '9a48e95ab320babb',
    ],
    54 => [
        'url' => 'https://deliveroo.com.kw/',
        'expect' => [
            'surface' => 'deliveroo.order',
        ],
        'detector' => 'a806daede3d53fc1',
    ],
    55 => [
        'url' => 'https://deliveroo.com/',
        'expect' => [
            'surface' => 'deliveroo.order',
        ],
        'detector' => 'da9bd2a660f0c555',
    ],
    56 => [
        'url' => 'https://deliveroo.fr/',
        'expect' => [
            'surface' => 'deliveroo.order',
        ],
        'detector' => 'ef85029ad161dd7c',
    ],
    57 => [
        'url' => 'https://deliveroo.hk/',
        'expect' => [
            'surface' => 'deliveroo.order',
        ],
        'detector' => 'a95288728db0332f',
    ],
    58 => [
        'url' => 'https://deliveroo.ie/',
        'expect' => [
            'surface' => 'deliveroo.order',
        ],
        'detector' => '3e59c38c24c3ac73',
    ],
    59 => [
        'url' => 'https://deliveroo.it/',
        'expect' => [
            'surface' => 'deliveroo.order',
        ],
        'detector' => '397410c232c55c56',
    ],
    60 => [
        'url' => 'https://deliveroo.nl/',
        'expect' => [
            'surface' => 'deliveroo.order',
        ],
        'detector' => 'ac30eb257f49cb7a',
    ],
    61 => [
        'url' => 'https://deliveroo.qa/',
        'expect' => [
            'surface' => 'deliveroo.order',
        ],
        'detector' => '05b4e6dbfec27419',
    ],
    62 => [
        'url' => 'https://deliveroo.sg/',
        'expect' => [
            'surface' => 'deliveroo.order',
        ],
        'detector' => '5002f3318cc6964c',
    ],
    63 => [
        'url' => 'https://depop.com/aaa',
        'expect' => [
            'surface' => 'depop.shop',
            'identifier' => 'aaa',
        ],
        'detector' => '4578a9be3e0e4eeb',
    ],
    64 => [
        'url' => 'https://dice.fm/artist/aaa',
        'expect' => [
            'surface' => 'dice.events',
            'identifier' => 'aaa',
        ],
        'detector' => '5dba8f18ed90fc88',
    ],
    65 => [
        'url' => 'https://discord.com/invite/aa',
        'expect' => [
            'surface' => 'discord.server',
            'identifier' => 'aa',
        ],
        'detector' => '4b7d5ee5547c1bee',
    ],
    66 => [
        'url' => 'https://discord.gg/aa',
        'expect' => [
            'surface' => 'discord.server',
            'identifier' => 'aa',
        ],
        'detector' => 'e6529ff88ed263ed',
    ],
    67 => [
        'url' => 'https://doordash.com/',
        'expect' => [
            'surface' => 'doordash.order',
        ],
        'detector' => 'ee08e818423fce07',
    ],
    68 => [
        'url' => 'https://dribbble.com/',
        'expect' => [
            'surface' => 'dribbble.profile',
        ],
        'detector' => '04d4e29145001e2d',
    ],
    69 => [
        'url' => 'https://dribbble.com/aa',
        'expect' => [
            'surface' => 'dribbble.profile',
            'identifier' => 'aa',
        ],
        'detector' => '08ecfc32ac9373c7',
    ],
    70 => [
        'url' => 'https://easi.com.au/',
        'expect' => [
            'surface' => 'easi.order',
        ],
        'detector' => 'fe1768d5b84af90b',
    ],
    71 => [
        'url' => 'https://easi.com/',
        'expect' => [
            'surface' => 'easi.order',
        ],
        'detector' => '35eb911b487cdeb4',
    ],
    72 => [
        'url' => 'https://easiglobal.com.au/',
        'expect' => [
            'surface' => 'easi.order',
        ],
        'detector' => 'fc8f7818b7e2d8c0',
    ],
    73 => [
        'url' => 'https://easiglobal.com/',
        'expect' => [
            'surface' => 'easi.order',
        ],
        'detector' => '7ef4dc73dfd9d6ed',
    ],
    74 => [
        'url' => 'https://eatapp.co/',
        'expect' => [
            'surface' => 'eat_app.reserve',
        ],
        'detector' => 'ec532214474a4231',
    ],
    75 => [
        'url' => 'https://etix.com/',
        'expect' => [
            'surface' => 'etix.tickets',
        ],
        'detector' => '212d4b87220e6de9',
    ],
    76 => [
        'url' => 'https://etsy.com/shop/aaa',
        'expect' => [
            'surface' => 'etsy.shop',
            'identifier' => 'aaa',
        ],
        'detector' => '24664939a435cd2c',
    ],
    77 => [
        'url' => 'https://eventbrite.at/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => 'c21a1c551c74fb12',
    ],
    78 => [
        'url' => 'https://eventbrite.be/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '857e8d0ee76896d5',
    ],
    79 => [
        'url' => 'https://eventbrite.ca/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => 'f1207b110d8a574c',
    ],
    80 => [
        'url' => 'https://eventbrite.ch/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '78b730edddfebfcc',
    ],
    81 => [
        'url' => 'https://eventbrite.cl/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '7e4e48852de3ba18',
    ],
    82 => [
        'url' => 'https://eventbrite.co.nz/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => 'ccde0626098cb3aa',
    ],
    83 => [
        'url' => 'https://eventbrite.co.uk/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '06dc09c86978ce76',
    ],
    84 => [
        'url' => 'https://eventbrite.com.ar/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => 'e59da6a4900b6e16',
    ],
    85 => [
        'url' => 'https://eventbrite.com.au/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '99eae40c346bff77',
    ],
    86 => [
        'url' => 'https://eventbrite.com.br/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => 'fe173955c987fc53',
    ],
    87 => [
        'url' => 'https://eventbrite.com.mx/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '59eaf500f7099365',
    ],
    88 => [
        'url' => 'https://eventbrite.com.pe/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '8cd95891b46792e3',
    ],
    89 => [
        'url' => 'https://eventbrite.com/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '54ea502d930a97d3',
    ],
    90 => [
        'url' => 'https://eventbrite.de/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => 'bb9b47ca0f5aa946',
    ],
    91 => [
        'url' => 'https://eventbrite.dk/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => 'f4906c207c970c22',
    ],
    92 => [
        'url' => 'https://eventbrite.es/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '0ea407e59eea50da',
    ],
    93 => [
        'url' => 'https://eventbrite.fi/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '10aac11f63244067',
    ],
    94 => [
        'url' => 'https://eventbrite.fr/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '72760a96e4658694',
    ],
    95 => [
        'url' => 'https://eventbrite.hk/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => 'cefb850f8b65dd7b',
    ],
    96 => [
        'url' => 'https://eventbrite.ie/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '5fd51f6e27750b4c',
    ],
    97 => [
        'url' => 'https://eventbrite.it/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => 'd33585026ef6cec6',
    ],
    98 => [
        'url' => 'https://eventbrite.nl/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '4c8e12bdb6478eed',
    ],
    99 => [
        'url' => 'https://eventbrite.pt/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '7695e14eada2946a',
    ],
    100 => [
        'url' => 'https://eventbrite.se/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => 'b0328a72b0830987',
    ],
    101 => [
        'url' => 'https://eventbrite.sg/o/aaa',
        'expect' => [
            'surface' => 'eventbrite.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => 'cfef92de2beeabc3',
    ],
    102 => [
        'url' => 'https://eventfinda.co.nz/',
        'expect' => [
            'surface' => 'eventfinda.tickets',
        ],
        'detector' => 'e8e113cd62a6447a',
    ],
    103 => [
        'url' => 'https://eventfinda.com.au/',
        'expect' => [
            'surface' => 'eventfinda.tickets',
        ],
        'detector' => '2c6205d5d2987788',
    ],
    104 => [
        'url' => 'https://eventfinda.com/',
        'expect' => [
            'surface' => 'eventfinda.tickets',
        ],
        'detector' => 'def71f08fef9d791',
    ],
    105 => [
        'url' => 'https://eventim.co.uk/',
        'expect' => [
            'surface' => 'eventim.tickets',
        ],
        'detector' => '3cfd280c5daa38cd',
    ],
    106 => [
        'url' => 'https://eventim.com/',
        'expect' => [
            'surface' => 'eventim.tickets',
        ],
        'detector' => '139dbf6ec3077a6a',
    ],
    107 => [
        'url' => 'https://eventim.de/',
        'expect' => [
            'surface' => 'eventim.tickets',
        ],
        'detector' => 'c01f69f5e7194db5',
    ],
    108 => [
        'url' => 'https://eventim.fr/',
        'expect' => [
            'surface' => 'eventim.tickets',
        ],
        'detector' => 'ab1b2246077326d6',
    ],
    109 => [
        'url' => 'https://eventim.nl/',
        'expect' => [
            'surface' => 'eventim.tickets',
        ],
        'detector' => 'ea99e46d76357b75',
    ],
    110 => [
        'url' => 'https://eventim.pl/',
        'expect' => [
            'surface' => 'eventim.tickets',
        ],
        'detector' => '083dabdeecae488f',
    ],
    111 => [
        'url' => 'https://exploretock.com/',
        'expect' => [
            'surface' => 'tock.reserve',
        ],
        'detector' => '239ba76ca60118b8',
    ],
    112 => [
        'url' => 'https://exploretock.com/aa',
        'expect' => [
            'surface' => 'tock.reserve',
            'identifier' => 'aa',
        ],
        'detector' => '9ebabc7fa2eaa514',
    ],
    113 => [
        'url' => 'https://facebook.com/a',
        'expect' => [
            'surface' => 'facebook.profile',
            'identifier' => 'a',
        ],
        'detector' => 'd78e03ab1ac96210',
    ],
    114 => [
        'url' => 'https://fareharbor.com/',
        'expect' => [
            'surface' => 'fareharbor.book',
        ],
        'detector' => '675c0ed455642038',
    ],
    115 => [
        'url' => 'https://fb.com/a',
        'expect' => [
            'surface' => 'facebook.profile',
            'identifier' => 'a',
        ],
        'detector' => '12b9e37ba910d214',
    ],
    116 => [
        'url' => 'https://feature.fm/',
        'expect' => [
            'surface' => 'feature_fm.release',
        ],
        'detector' => 'a64733da7f7387b4',
    ],
    117 => [
        'url' => 'https://ffm.to/',
        'expect' => [
            'surface' => 'feature_fm.release',
        ],
        'detector' => 'fc6ca35730c06922',
    ],
    118 => [
        'url' => 'https://fiverr.com/aaa',
        'expect' => [
            'surface' => 'fiverr.profile',
            'identifier' => 'aaa',
        ],
        'detector' => '233ab86edb7507a6',
    ],
    119 => [
        'url' => 'https://flickr.com/photos/aa',
        'expect' => [
            'surface' => 'flickr.photos',
            'identifier' => 'aa',
        ],
        'detector' => '348e8438b852aa15',
    ],
    120 => [
        'url' => 'https://fresha.com/a/aaa',
        'expect' => [
            'surface' => 'fresha.book',
            'identifier' => 'aaa',
        ],
        'detector' => 'cb5525db472c96a4',
    ],
    121 => [
        'url' => 'https://genbook.com/',
        'expect' => [
            'surface' => 'genbook.book',
        ],
        'detector' => '3208a1e9edd198b2',
    ],
    122 => [
        'url' => 'https://github.com/',
        'expect' => [
            'surface' => 'github.profile',
        ],
        'detector' => 'b6c3381b02805e19',
    ],
    123 => [
        'url' => 'https://github.com/aa',
        'expect' => [
            'surface' => 'github.profile',
            'identifier' => 'aa',
        ],
        'detector' => 'b19f46863fac33c6',
    ],
    124 => [
        'url' => 'https://gitlab.com/',
        'expect' => [
            'surface' => 'gitlab.profile',
        ],
        'detector' => '183447e28bf2106c',
    ],
    125 => [
        'url' => 'https://gitlab.com/aa',
        'expect' => [
            'surface' => 'gitlab.profile',
            'identifier' => 'aa',
        ],
        'detector' => '3a883afeae0ffb24',
    ],
    126 => [
        'url' => 'https://glossgenius.com/',
        'expect' => [
            'surface' => 'glossgenius.book',
        ],
        'detector' => '58b11f030ba773d9',
    ],
    127 => [
        'url' => 'https://google.com/calendar/appointments',
        'expect' => [
            'surface' => 'google_appointments.book',
        ],
        'detector' => '5b05914c4d6e635c',
    ],
    128 => [
        'url' => 'https://grubhub.com/',
        'expect' => [
            'surface' => 'grubhub.order',
        ],
        'detector' => 'aeb8fbf2eb83b6a6',
    ],
    129 => [
        'url' => 'https://gumroad.com/',
        'expect' => [
            'surface' => 'gumroad.store',
        ],
        'detector' => '0b4b9a4c1636dbe4',
    ],
    130 => [
        'url' => 'https://halaxy.com/',
        'expect' => [
            'surface' => 'halaxy.book',
        ],
        'detector' => 'f8c7c4da29c5a248',
    ],
    131 => [
        'url' => 'https://heyzine.com/',
        'expect' => [
            'surface' => 'heyzine.publication',
        ],
        'detector' => 'cf4fe9ec6ab15298',
    ],
    132 => [
        'url' => 'https://hflip.co/',
        'expect' => [
            'surface' => 'heyzine.publication',
        ],
        'detector' => 'bf721858f5656dfc',
    ],
    133 => [
        'url' => 'https://hotdoc.com.au/',
        'expect' => [
            'surface' => 'hotdoc.book',
        ],
        'detector' => 'aa86373960ff3953',
    ],
    134 => [
        'url' => 'https://houzz.com.au/professionals/aaa/aaa',
        'expect' => [
            'surface' => 'houzz.pro',
            'identifier' => 'aaa',
        ],
        'detector' => '796978399b9de232',
    ],
    135 => [
        'url' => 'https://houzz.com/professionals/aaa/aaa',
        'expect' => [
            'surface' => 'houzz.pro',
            'identifier' => 'aaa',
        ],
        'detector' => 'e3d40499f15e17c6',
    ],
    136 => [
        'url' => 'https://humanitix.com/host/aaa',
        'expect' => [
            'surface' => 'humanitix.organiser',
            'identifier' => 'aaa',
        ],
        'detector' => '4956e516be3b66c5',
    ],
    137 => [
        'url' => 'https://hungrypanda.co/',
        'expect' => [
            'surface' => 'hungrypanda.order',
        ],
        'detector' => 'd76893ba620b3281',
    ],
    138 => [
        'url' => 'https://instagram.com/a',
        'expect' => [
            'surface' => 'instagram.profile',
            'identifier' => 'a',
        ],
        'detector' => '87d16f0666ed1999',
    ],
    139 => [
        'url' => 'https://janeapp.com/',
        'expect' => [
            'surface' => 'jane_app.book',
        ],
        'detector' => '721cf7340e7d59d5',
    ],
    140 => [
        'url' => 'https://joinblvd.com/',
        'expect' => [
            'surface' => 'boulevard.book',
        ],
        'detector' => 'e41f09f90ecd8c99',
    ],
    141 => [
        'url' => 'https://just-eat.ch/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => 'bb58273c26e364cc',
    ],
    142 => [
        'url' => 'https://just-eat.co.uk/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => '76aa62cb03d7624d',
    ],
    143 => [
        'url' => 'https://just-eat.com/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => 'bcbc54297d5f6977',
    ],
    144 => [
        'url' => 'https://just-eat.dk/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => '6d3b32c19fc720ce',
    ],
    145 => [
        'url' => 'https://just-eat.es/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => 'ef5255bee2a2f499',
    ],
    146 => [
        'url' => 'https://just-eat.fr/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => '20d6afa5758123de',
    ],
    147 => [
        'url' => 'https://just-eat.ie/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => '3b7d53ce57615f1b',
    ],
    148 => [
        'url' => 'https://just-eat.it/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => 'e64a04db96abf0de',
    ],
    149 => [
        'url' => 'https://just-eat.lu/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => '6ea9978982cb2858',
    ],
    150 => [
        'url' => 'https://just-eat.no/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => 'c9538023314246ec',
    ],
    151 => [
        'url' => 'https://justeat.ch/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => 'b04b0380b9670bea',
    ],
    152 => [
        'url' => 'https://justeat.co.uk/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => '8528c3162eb1cf46',
    ],
    153 => [
        'url' => 'https://justeat.com/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => '8f32929b96c3e0e4',
    ],
    154 => [
        'url' => 'https://justeat.dk/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => 'b8ad6ee96fe73899',
    ],
    155 => [
        'url' => 'https://justeat.es/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => 'b08ab37da47f29df',
    ],
    156 => [
        'url' => 'https://justeat.fr/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => 'fa8d288e0dd1df23',
    ],
    157 => [
        'url' => 'https://justeat.ie/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => 'ea5ca117d0f8f11a',
    ],
    158 => [
        'url' => 'https://justeat.it/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => 'ae388a8c2eb465e5',
    ],
    159 => [
        'url' => 'https://justeat.lu/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => 'e68ee5e08f10bfee',
    ],
    160 => [
        'url' => 'https://justeat.no/',
        'expect' => [
            'surface' => 'just_eat.order',
        ],
        'detector' => '3655b27f5b99ea79',
    ],
    161 => [
        'url' => 'https://kick.com/aaa',
        'expect' => [
            'surface' => 'kick.channel',
            'identifier' => 'aaa',
        ],
        'detector' => '77ca38fc36e5401f',
    ],
    162 => [
        'url' => 'https://kitomba.com/',
        'expect' => [
            'surface' => 'kitomba.book',
        ],
        'detector' => 'e0ffa0738483e4e5',
    ],
    163 => [
        'url' => 'https://ko-fi.com/',
        'expect' => [
            'surface' => 'ko_fi.page',
        ],
        'detector' => 'fe90cb898c3bdfda',
    ],
    164 => [
        'url' => 'https://ko-fi.com/aa',
        'expect' => [
            'surface' => 'ko_fi.page',
            'identifier' => 'aa',
        ],
        'detector' => 'e99acec5f19f92f6',
    ],
    165 => [
        'url' => 'https://laylo.com/',
        'expect' => [
            'surface' => 'laylo.drop',
        ],
        'detector' => '312ee55ab7d2d088',
    ],
    166 => [
        'url' => 'https://libro.fm/',
        'expect' => [
            'surface' => 'libro_fm.store',
        ],
        'detector' => '69b8aceb6c6b6cc1',
    ],
    167 => [
        'url' => 'https://linkedin.com/in/aa',
        'expect' => [
            'surface' => 'linkedin.profile',
            'identifier' => 'aa',
        ],
        'detector' => '75556c5a19e1eba2',
    ],
    168 => [
        'url' => 'https://linkfire.com/',
        'expect' => [
            'surface' => 'linkfire.release',
        ],
        'detector' => 'dcab1b2fbc7ade36',
    ],
    169 => [
        'url' => 'https://lnk.to/',
        'expect' => [
            'surface' => 'linkfire.release',
        ],
        'detector' => 'e9d6bc3cda5efe0c',
    ],
    170 => [
        'url' => 'https://lu.ma/user/aa',
        'expect' => [
            'surface' => 'luma.calendar',
            'identifier' => 'aa',
        ],
        'detector' => '78c2099e5558ad1f',
    ],
    171 => [
        'url' => 'https://mangomint.com/',
        'expect' => [
            'surface' => 'mangomint.book',
        ],
        'detector' => '8bcc43fde2f555f8',
    ],
    172 => [
        'url' => 'https://meandu.com/',
        'expect' => [
            'surface' => 'mr_yum.order',
        ],
        'detector' => '57f63ca7d8e03255',
    ],
    173 => [
        'url' => 'https://medium.com/@aa',
        'expect' => [
            'surface' => 'medium.profile',
            'identifier' => 'aa',
        ],
        'detector' => '1e90b50adf18becf',
    ],
    174 => [
        'url' => 'https://megatix.com.au/',
        'expect' => [
            'surface' => 'megatix.tickets',
        ],
        'detector' => 'da86f4028ebed1ed',
    ],
    175 => [
        'url' => 'https://menulog.com.au/',
        'expect' => [
            'surface' => 'menulog.order',
        ],
        'detector' => 'b8023d95302493ed',
    ],
    176 => [
        'url' => 'https://mindbodyonline.com/',
        'expect' => [
            'surface' => 'mindbody.book',
        ],
        'detector' => '6cca92df6cece15d',
    ],
    177 => [
        'url' => 'https://mixcloud.com/',
        'expect' => [
            'surface' => 'mixcloud.player',
        ],
        'detector' => '5f8da8c1d727d9bf',
    ],
    178 => [
        'url' => 'https://mixcloud.com/aa',
        'expect' => [
            'surface' => 'mixcloud.player',
            'identifier' => 'aa',
        ],
        'detector' => '1cc4ffe453245fc6',
    ],
    179 => [
        'url' => 'https://moshtix.com.au/',
        'expect' => [
            'surface' => 'moshtix.tickets',
        ],
        'detector' => 'e3ce25e703402b08',
    ],
    180 => [
        'url' => 'https://mryum.com/',
        'expect' => [
            'surface' => 'mr_yum.order',
        ],
        'detector' => '06eef592c464ceaf',
    ],
    181 => [
        'url' => 'https://music.apple.com/artist/1',
        'expect' => [
            'surface' => 'apple_music.artist',
            'identifier' => '1',
        ],
        'detector' => 'a013bd51e02c8976',
    ],
    182 => [
        'url' => 'https://music.youtube.com/channel/UCaaaaaaaaaaaaaaaaaaaaaa',
        'expect' => [
            'surface' => 'youtube_music.channel',
            'identifier' => 'UCaaaaaaaaaaaaaaaaaaaaaa',
        ],
        'detector' => 'd260dead7b0768a3',
    ],
    183 => [
        'url' => 'https://noterro.com/',
        'expect' => [
            'surface' => 'noterro.book',
        ],
        'detector' => '62486d28216a3e4c',
    ],
    184 => [
        'url' => 'https://obee.com.au/',
        'expect' => [
            'surface' => 'obee.reserve',
        ],
        'detector' => '6d94e24c6ddaf634',
    ],
    185 => [
        'url' => 'https://obeeapp.com/',
        'expect' => [
            'surface' => 'obee.reserve',
        ],
        'detector' => 'a4e3b4f785c4bdd3',
    ],
    186 => [
        'url' => 'https://office.com/bookwithme/',
        'expect' => [
            'surface' => 'microsoft_bookings.book',
        ],
        'detector' => '51ab4431e808a652',
    ],
    187 => [
        'url' => 'https://office365.com/bookings/',
        'expect' => [
            'surface' => 'microsoft_bookings.book',
        ],
        'detector' => '22b964b81d26e938',
    ],
    188 => [
        'url' => 'https://open.spotify.com/artist/aaa',
        'expect' => [
            'surface' => 'spotify.player',
            'identifier' => 'aaa',
        ],
        'detector' => 'c8ec1b8650ca53b2',
    ],
    189 => [
        'url' => 'https://opentable.ae/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '8ba3a392e622986b',
    ],
    190 => [
        'url' => 'https://opentable.ae/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => 'bc4dbc0aaa7e0936',
    ],
    191 => [
        'url' => 'https://opentable.ae/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => 'f41ad20a2e9b9d84',
    ],
    192 => [
        'url' => 'https://opentable.at/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => 'cd5977093c8d3768',
    ],
    193 => [
        'url' => 'https://opentable.at/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '99c3fa11e0ae49b8',
    ],
    194 => [
        'url' => 'https://opentable.at/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => '17a35e751d44af73',
    ],
    195 => [
        'url' => 'https://opentable.ca/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => 'af430b15f77238a2',
    ],
    196 => [
        'url' => 'https://opentable.ca/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '1546dc07ab719f25',
    ],
    197 => [
        'url' => 'https://opentable.ca/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => '5983a48e72449cd3',
    ],
    198 => [
        'url' => 'https://opentable.co.th/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '8d1109289710ea27',
    ],
    199 => [
        'url' => 'https://opentable.co.th/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => 'e1991bead500c8ec',
    ],
    200 => [
        'url' => 'https://opentable.co.th/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => '3d3e73d705ae78f3',
    ],
    201 => [
        'url' => 'https://opentable.co.uk/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '50a20d159e784aec',
    ],
    202 => [
        'url' => 'https://opentable.co.uk/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => 'c7fabf59c5a481ee',
    ],
    203 => [
        'url' => 'https://opentable.co.uk/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => 'bebbbbe2c2f6bc99',
    ],
    204 => [
        'url' => 'https://opentable.com.au/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '0db07f6e1bc44f87',
    ],
    205 => [
        'url' => 'https://opentable.com.au/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '9e785905e6ad67d6',
    ],
    206 => [
        'url' => 'https://opentable.com.au/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => '3f2a5d74611b25d1',
    ],
    207 => [
        'url' => 'https://opentable.com.mx/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '89d5bc6da67eb3c6',
    ],
    208 => [
        'url' => 'https://opentable.com.mx/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '0ea9147e0bb3426a',
    ],
    209 => [
        'url' => 'https://opentable.com.mx/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => '5d74763657eb65c4',
    ],
    210 => [
        'url' => 'https://opentable.com/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '9eda6310b42ff63a',
    ],
    211 => [
        'url' => 'https://opentable.com/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '4649197e747236e0',
    ],
    212 => [
        'url' => 'https://opentable.com/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => 'e2b6f3d2721b2f10',
    ],
    213 => [
        'url' => 'https://opentable.de/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => 'af02e226ad4ae6df',
    ],
    214 => [
        'url' => 'https://opentable.de/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '788fff533be07e90',
    ],
    215 => [
        'url' => 'https://opentable.de/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => '98525c21146dec16',
    ],
    216 => [
        'url' => 'https://opentable.es/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => 'c2d69a6dff5f6425',
    ],
    217 => [
        'url' => 'https://opentable.es/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '1f691d33d6f225d3',
    ],
    218 => [
        'url' => 'https://opentable.es/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => '20e93bbba530d7cd',
    ],
    219 => [
        'url' => 'https://opentable.hk/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '7b522cf1dd385dcf',
    ],
    220 => [
        'url' => 'https://opentable.hk/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '64aba0369a8ada33',
    ],
    221 => [
        'url' => 'https://opentable.hk/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => '3a1e7a568d1049bb',
    ],
    222 => [
        'url' => 'https://opentable.ie/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => 'eeee30225a3ffe82',
    ],
    223 => [
        'url' => 'https://opentable.ie/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '36a8f03ebae019f8',
    ],
    224 => [
        'url' => 'https://opentable.ie/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => '8b7dd98a090b9c4b',
    ],
    225 => [
        'url' => 'https://opentable.it/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '43b45d158368b673',
    ],
    226 => [
        'url' => 'https://opentable.it/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '522df576e2748819',
    ],
    227 => [
        'url' => 'https://opentable.it/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => '7d735502a86617ca',
    ],
    228 => [
        'url' => 'https://opentable.jp/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '2fc431ee6b4aed5f',
    ],
    229 => [
        'url' => 'https://opentable.jp/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => 'c46e110a9bb757e3',
    ],
    230 => [
        'url' => 'https://opentable.jp/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => 'd29516a29ac31d94',
    ],
    231 => [
        'url' => 'https://opentable.nl/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '1d35d37e3a42e0fc',
    ],
    232 => [
        'url' => 'https://opentable.nl/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => 'cb7c545a50553588',
    ],
    233 => [
        'url' => 'https://opentable.nl/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => '1f520e3af1ef3b6d',
    ],
    234 => [
        'url' => 'https://opentable.sg/?restRef=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '026b2ec99da6dc0f',
    ],
    235 => [
        'url' => 'https://opentable.sg/?rid=100000',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '100000',
        ],
        'detector' => '856f2c7a9f02e9e9',
    ],
    236 => [
        'url' => 'https://opentable.sg/restaurant/profile/1',
        'expect' => [
            'surface' => 'opentable.reserve',
            'identifier' => '1',
        ],
        'detector' => '61dc018682c89305',
    ],
    237 => [
        'url' => 'https://orcd.co/',
        'expect' => [
            'surface' => 'orchard.release',
        ],
        'detector' => 'fe65605d40535e1d',
    ],
    238 => [
        'url' => 'https://order.online/',
        'expect' => [
            'surface' => 'order_online.order',
        ],
        'detector' => '8f1d87a21601969d',
    ],
    239 => [
        'url' => 'https://ordermate.online/',
        'expect' => [
            'surface' => 'ordermate.order',
        ],
        'detector' => '0b4d0eb6272930ac',
    ],
    240 => [
        'url' => 'https://ovatu.com/',
        'expect' => [
            'surface' => 'ovatu.book',
        ],
        'detector' => '55f20100ac6643e3',
    ],
    241 => [
        'url' => 'https://oztix.com.au/',
        'expect' => [
            'surface' => 'oztix.tickets',
        ],
        'detector' => '716b33f6e22319d8',
    ],
    242 => [
        'url' => 'https://partiful.com/u/aaa',
        'expect' => [
            'surface' => 'partiful.events',
            'identifier' => 'aaa',
        ],
        'detector' => 'addba2bc7a4fd21c',
    ],
    243 => [
        'url' => 'https://patreon.com/',
        'expect' => [
            'surface' => 'patreon.page',
        ],
        'detector' => 'ac9bc8854053d831',
    ],
    244 => [
        'url' => 'https://patreon.com/aa',
        'expect' => [
            'surface' => 'patreon.page',
            'identifier' => 'aa',
        ],
        'detector' => '7260c9bcc514597b',
    ],
    245 => [
        'url' => 'https://paypal.com/paypalme/aa',
        'expect' => [
            'surface' => 'paypal.me',
            'identifier' => 'aa',
        ],
        'detector' => 'd17db85e06ed8d35',
    ],
    246 => [
        'url' => 'https://paypal.me/aa',
        'expect' => [
            'surface' => 'paypal.me',
            'identifier' => 'aa',
        ],
        'detector' => '6c3f9bc2fc129f91',
    ],
    247 => [
        'url' => 'https://phorest.com/',
        'expect' => [
            'surface' => 'phorest.book',
        ],
        'detector' => '9368ab289001f37b',
    ],
    248 => [
        'url' => 'https://pinterest.com/aaa',
        'expect' => [
            'surface' => 'pinterest.profile',
            'identifier' => 'aaa',
        ],
        'detector' => '7f05ebab64a5a309',
    ],
    249 => [
        'url' => 'https://podcasts.apple.com/podcast/id1',
        'expect' => [
            'surface' => 'apple_podcasts.show',
            'identifier' => '1',
        ],
        'detector' => '649cd477e1185e84',
    ],
    250 => [
        'url' => 'https://productreview.com.au/listings/aaa',
        'expect' => [
            'surface' => 'productreview.listing',
            'identifier' => 'aaa',
        ],
        'detector' => '0c41b690787df8e7',
    ],
    251 => [
        'url' => 'https://quandoo.at/',
        'expect' => [
            'surface' => 'quandoo.reserve',
        ],
        'detector' => 'ba97caaff5f8e45c',
    ],
    252 => [
        'url' => 'https://quandoo.ch/',
        'expect' => [
            'surface' => 'quandoo.reserve',
        ],
        'detector' => '3b1be6a8182b8039',
    ],
    253 => [
        'url' => 'https://quandoo.co.uk/',
        'expect' => [
            'surface' => 'quandoo.reserve',
        ],
        'detector' => 'dab1fbfb8661067d',
    ],
    254 => [
        'url' => 'https://quandoo.com.au/',
        'expect' => [
            'surface' => 'quandoo.reserve',
        ],
        'detector' => '693412fc531e6da3',
    ],
    255 => [
        'url' => 'https://quandoo.com/',
        'expect' => [
            'surface' => 'quandoo.reserve',
        ],
        'detector' => 'ee929d5600771559',
    ],
    256 => [
        'url' => 'https://quandoo.de/',
        'expect' => [
            'surface' => 'quandoo.reserve',
        ],
        'detector' => '4cf12025413842a5',
    ],
    257 => [
        'url' => 'https://quandoo.fi/',
        'expect' => [
            'surface' => 'quandoo.reserve',
        ],
        'detector' => '001fd6d5b07a7d87',
    ],
    258 => [
        'url' => 'https://quandoo.hk/',
        'expect' => [
            'surface' => 'quandoo.reserve',
        ],
        'detector' => 'b5c3ec57575b3b7f',
    ],
    259 => [
        'url' => 'https://quandoo.it/',
        'expect' => [
            'surface' => 'quandoo.reserve',
        ],
        'detector' => 'ebd07ebefcfb971a',
    ],
    260 => [
        'url' => 'https://quandoo.nl/',
        'expect' => [
            'surface' => 'quandoo.reserve',
        ],
        'detector' => '105bc0d306d1a903',
    ],
    261 => [
        'url' => 'https://quandoo.sg/',
        'expect' => [
            'surface' => 'quandoo.reserve',
        ],
        'detector' => '619e127fd887977a',
    ],
    262 => [
        'url' => 'https://ra.co/',
        'expect' => [
            'surface' => 'resident_advisor.tickets',
        ],
        'detector' => '444ffe8a0fa8709f',
    ],
    263 => [
        'url' => 'https://ra.co/dj/aa',
        'expect' => [
            'surface' => 'resident_advisor.tickets',
            'identifier' => 'aa',
        ],
        'detector' => '4ef46120f0239c3b',
    ],
    264 => [
        'url' => 'https://redbubble.com/people/aa',
        'expect' => [
            'surface' => 'redbubble.shop',
            'identifier' => 'aa',
        ],
        'detector' => '371ce61e38a98175',
    ],
    265 => [
        'url' => 'https://reddit.com/u/aa',
        'expect' => [
            'surface' => 'reddit.profile',
            'identifier' => 'aa',
        ],
        'detector' => '054ffe1abb69e6bb',
    ],
    266 => [
        'url' => 'https://resdiary.com/restaurant/aaa',
        'expect' => [
            'surface' => 'resdiary.reserve',
            'identifier' => 'aaa',
        ],
        'detector' => '2bd2087df3ff123a',
    ],
    267 => [
        'url' => 'https://resdiary.com/widget/aaa/aaa',
        'expect' => [
            'surface' => 'resdiary.reserve',
            'identifier' => 'aaa',
        ],
        'detector' => '2e4b33528297c23b',
    ],
    268 => [
        'url' => 'https://resy.com/',
        'expect' => [
            'surface' => 'resy.reserve',
        ],
        'detector' => 'e13599cb38227ab7',
    ],
    269 => [
        'url' => 'https://rezdy.com/',
        'expect' => [
            'surface' => 'rezdy.book',
        ],
        'detector' => '168e2991df2480ea',
    ],
    270 => [
        'url' => 'https://rumble.com/c/aa',
        'expect' => [
            'surface' => 'rumble.channel',
            'identifier' => 'aa',
        ],
        'detector' => '3435affbf3f16e98',
    ],
    271 => [
        'url' => 'https://schedulicity.com/',
        'expect' => [
            'surface' => 'schedulicity.book',
        ],
        'detector' => '3db2848fdbc3f084',
    ],
    272 => [
        'url' => 'https://seetickets.com/',
        'expect' => [
            'surface' => 'see_tickets.tickets',
        ],
        'detector' => '6ee7ac923cc46055',
    ],
    273 => [
        'url' => 'https://sevenrooms.com/',
        'expect' => [
            'surface' => 'sevenrooms.reserve',
        ],
        'detector' => 'c245e4096dc619cf',
    ],
    274 => [
        'url' => 'https://shortcuts.com.au/',
        'expect' => [
            'surface' => 'shortcuts.book',
        ],
        'detector' => '6928abc0782f6312',
    ],
    275 => [
        'url' => 'https://shortcuts.net/',
        'expect' => [
            'surface' => 'shortcuts.book',
        ],
        'detector' => 'f2a80713a0c31316',
    ],
    276 => [
        'url' => 'https://simplybook.it/',
        'expect' => [
            'surface' => 'simplybook_me.book',
        ],
        'detector' => '0492d148a2d30722',
    ],
    277 => [
        'url' => 'https://skiddle.com/',
        'expect' => [
            'surface' => 'skiddle.tickets',
        ],
        'detector' => '899a958137a1dda7',
    ],
    278 => [
        'url' => 'https://skipthedishes.com/',
        'expect' => [
            'surface' => 'skipthedishes.order',
        ],
        'detector' => 'fcd0cb4f31067acd',
    ],
    279 => [
        'url' => 'https://slicelife.com/',
        'expect' => [
            'surface' => 'slice.order',
        ],
        'detector' => '513fb3089dbc9112',
    ],
    280 => [
        'url' => 'https://snapchat.com/add/aaa',
        'expect' => [
            'surface' => 'snapchat.profile',
            'identifier' => 'aaa',
        ],
        'detector' => '9cf65cb83dba2bf1',
    ],
    281 => [
        'url' => 'https://songkick.com/artists/1',
        'expect' => [
            'surface' => 'songkick.artist',
            'identifier' => '1',
        ],
        'detector' => '11b40990963d324f',
    ],
    282 => [
        'url' => 'https://soundcloud.com/aaa',
        'expect' => [
            'surface' => 'soundcloud.player',
            'identifier' => 'aaa',
        ],
        'detector' => '5d1faaba140ed77a',
    ],
    283 => [
        'url' => 'https://square.link/aaaaaa',
        'expect' => [
            'surface' => 'square.payment_link',
        ],
        'detector' => '72aa9a233221d1ae',
    ],
    284 => [
        'url' => 'https://squarespace.com/',
        'expect' => [
            'surface' => 'squarespace.store',
        ],
        'detector' => 'c0e240afa37ec5e0',
    ],
    285 => [
        'url' => 'https://squareup.com/',
        'expect' => [
            'surface' => 'square.book',
        ],
        'detector' => '8991ee8ff4aeb1d5',
    ],
    286 => [
        'url' => 'https://stan.store/aa',
        'expect' => [
            'surface' => 'stan.store',
            'identifier' => 'aa',
        ],
        'detector' => '5d0175832e04f6d8',
    ],
    287 => [
        'url' => 'https://strava.com/clubs/aaa',
        'expect' => [
            'surface' => 'strava.club',
            'identifier' => 'aaa',
        ],
        'detector' => '448fb3d7693c9029',
    ],
    288 => [
        'url' => 'https://styleseat.com/',
        'expect' => [
            'surface' => 'styleseat.book',
        ],
        'detector' => 'eea15ecd3aef19b1',
    ],
    289 => [
        'url' => 'https://substack.com/',
        'expect' => [
            'surface' => 'substack.publication',
        ],
        'detector' => 'fc489321f37fbb1a',
    ],
    290 => [
        'url' => 'https://tablecheck.com/',
        'expect' => [
            'surface' => 'tablecheck.reserve',
        ],
        'detector' => 'f13c8e2e611a42da',
    ],
    291 => [
        'url' => 'https://tablein.com/',
        'expect' => [
            'surface' => 'tablein.reserve',
        ],
        'detector' => '4380291f0d1de922',
    ],
    292 => [
        'url' => 'https://telegram.me/aaaaa',
        'expect' => [
            'surface' => 'telegram.channel',
            'identifier' => 'aaaaa',
        ],
        'detector' => 'ff54ee98bd6fda4a',
    ],
    293 => [
        'url' => 'https://telegram.org/aaaaa',
        'expect' => [
            'surface' => 'telegram.channel',
            'identifier' => 'aaaaa',
        ],
        'detector' => 'e2bab5851bb13bf4',
    ],
    294 => [
        'url' => 'https://thefork.at/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => 'e24ebf8d39eee599',
    ],
    295 => [
        'url' => 'https://thefork.be/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => 'dcf2e811ea0b7666',
    ],
    296 => [
        'url' => 'https://thefork.ch/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => 'a287757eb0d497f9',
    ],
    297 => [
        'url' => 'https://thefork.cl/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => 'b18d73ebf7b7ef3f',
    ],
    298 => [
        'url' => 'https://thefork.co.uk/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => 'b4998c27bfc88e1a',
    ],
    299 => [
        'url' => 'https://thefork.com.ar/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => '0cf61c1e9973c404',
    ],
    300 => [
        'url' => 'https://thefork.com.au/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => '327caa46025b76fe',
    ],
    301 => [
        'url' => 'https://thefork.com.br/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => '58da97b5234b4906',
    ],
    302 => [
        'url' => 'https://thefork.com/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => 'b4d6fceb9afc8ced',
    ],
    303 => [
        'url' => 'https://thefork.de/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => '3b7376435d930976',
    ],
    304 => [
        'url' => 'https://thefork.dk/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => '6f0a93fa69e23359',
    ],
    305 => [
        'url' => 'https://thefork.es/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => '96c44cd3954ecf5e',
    ],
    306 => [
        'url' => 'https://thefork.fr/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => '3f94296aa7196a6d',
    ],
    307 => [
        'url' => 'https://thefork.it/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => 'e7c42ef121fc3634',
    ],
    308 => [
        'url' => 'https://thefork.nl/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => 'a9e60004fa6971fc',
    ],
    309 => [
        'url' => 'https://thefork.pt/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => '84c07ad427eef038',
    ],
    310 => [
        'url' => 'https://thefork.se/',
        'expect' => [
            'surface' => 'thefork.reserve',
        ],
        'detector' => '08bfdf186659a603',
    ],
    311 => [
        'url' => 'https://threads.com/a',
        'expect' => [
            'surface' => 'threads.profile',
            'identifier' => 'a',
        ],
        'detector' => '830dc3cb0c059fdb',
    ],
    312 => [
        'url' => 'https://threads.net/a',
        'expect' => [
            'surface' => 'threads.profile',
            'identifier' => 'a',
        ],
        'detector' => 'a77924a4fbb8be6c',
    ],
    313 => [
        'url' => 'https://ticketek.co.nz/',
        'expect' => [
            'surface' => 'ticketek.tickets',
        ],
        'detector' => '626cc44bd4c8910e',
    ],
    314 => [
        'url' => 'https://ticketek.com.ar/',
        'expect' => [
            'surface' => 'ticketek.tickets',
        ],
        'detector' => '9951594e05c2f2e2',
    ],
    315 => [
        'url' => 'https://ticketek.com.au/',
        'expect' => [
            'surface' => 'ticketek.tickets',
        ],
        'detector' => '92cd60a128909592',
    ],
    316 => [
        'url' => 'https://ticketek.com/',
        'expect' => [
            'surface' => 'ticketek.tickets',
        ],
        'detector' => 'a3c230b1da461743',
    ],
    317 => [
        'url' => 'https://ticketmaster.ae/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => '03e13970e9d4a4fd',
    ],
    318 => [
        'url' => 'https://ticketmaster.at/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => 'fcc6469808eb7e0b',
    ],
    319 => [
        'url' => 'https://ticketmaster.be/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => 'bd90664c1684fd37',
    ],
    320 => [
        'url' => 'https://ticketmaster.ca/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => '412647742deef43c',
    ],
    321 => [
        'url' => 'https://ticketmaster.ch/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => '62f87001cd0db810',
    ],
    322 => [
        'url' => 'https://ticketmaster.co.nz/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => 'bd1326b884503e84',
    ],
    323 => [
        'url' => 'https://ticketmaster.co.uk/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => '5628190b2b39ae20',
    ],
    324 => [
        'url' => 'https://ticketmaster.com.au/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => '96c8399173bf8591',
    ],
    325 => [
        'url' => 'https://ticketmaster.com.mx/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => 'a5a39eebf99a97cc',
    ],
    326 => [
        'url' => 'https://ticketmaster.com/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => '3b513fc413e7a1eb',
    ],
    327 => [
        'url' => 'https://ticketmaster.de/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => '3b0a5d7663d86645',
    ],
    328 => [
        'url' => 'https://ticketmaster.dk/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => '81083c506d58907c',
    ],
    329 => [
        'url' => 'https://ticketmaster.es/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => 'c15db8b10abf7808',
    ],
    330 => [
        'url' => 'https://ticketmaster.fi/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => '3191e76b32cb8199',
    ],
    331 => [
        'url' => 'https://ticketmaster.fr/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => 'e2d530e723471d22',
    ],
    332 => [
        'url' => 'https://ticketmaster.ie/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => '2ca19a6fcf7ee0bd',
    ],
    333 => [
        'url' => 'https://ticketmaster.it/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => '9ef542107027b1d6',
    ],
    334 => [
        'url' => 'https://ticketmaster.nl/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => '53a1781e408e16a8',
    ],
    335 => [
        'url' => 'https://ticketmaster.no/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => 'ca514879bf136562',
    ],
    336 => [
        'url' => 'https://ticketmaster.se/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => '83a0ad68f5949589',
    ],
    337 => [
        'url' => 'https://ticketmaster.sg/',
        'expect' => [
            'surface' => 'ticketmaster.tickets',
        ],
        'detector' => 'b2ee6b797f5e7dee',
    ],
    338 => [
        'url' => 'https://ticketweb.ca/',
        'expect' => [
            'surface' => 'ticketweb.tickets',
        ],
        'detector' => 'b72ed5e4e6064211',
    ],
    339 => [
        'url' => 'https://ticketweb.co.uk/',
        'expect' => [
            'surface' => 'ticketweb.tickets',
        ],
        'detector' => '1e2e8cc0a7ce827c',
    ],
    340 => [
        'url' => 'https://ticketweb.com/',
        'expect' => [
            'surface' => 'ticketweb.tickets',
        ],
        'detector' => 'c26654f403f21eb0',
    ],
    341 => [
        'url' => 'https://tidal.com/',
        'expect' => [
            'surface' => 'tidal.player',
        ],
        'detector' => '8e776b101d9c4d50',
    ],
    342 => [
        'url' => 'https://tidal.com/artist/1',
        'expect' => [
            'surface' => 'tidal.player',
            'identifier' => '1',
        ],
        'detector' => 'fb9f96042bd085e2',
    ],
    343 => [
        'url' => 'https://tiktok.com/@aaa',
        'expect' => [
            'surface' => 'tiktok.profile',
            'identifier' => 'aaa',
        ],
        'detector' => 'c5c2cd31010b8491',
    ],
    344 => [
        'url' => 'https://tixr.com/',
        'expect' => [
            'surface' => 'tixr.tickets',
        ],
        'detector' => '45638c4225d3d6f4',
    ],
    345 => [
        'url' => 'https://toasttab.com/',
        'expect' => [
            'surface' => 'toast.order',
        ],
        'detector' => '3464b536382abf14',
    ],
    346 => [
        'url' => 'https://tock.com/',
        'expect' => [
            'surface' => 'tock.reserve',
        ],
        'detector' => '167a703875b8fb8e',
    ],
    347 => [
        'url' => 'https://treatwell.at/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => 'abf318864eb6e6b5',
    ],
    348 => [
        'url' => 'https://treatwell.be/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => '3c33da75f4370ff5',
    ],
    349 => [
        'url' => 'https://treatwell.ch/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => '6db3db35bb01858e',
    ],
    350 => [
        'url' => 'https://treatwell.co.uk/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => 'bbaf7149016c541b',
    ],
    351 => [
        'url' => 'https://treatwell.com/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => 'de05b67e56298062',
    ],
    352 => [
        'url' => 'https://treatwell.de/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => '6453336f16818f92',
    ],
    353 => [
        'url' => 'https://treatwell.es/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => 'fb008a3f0168750c',
    ],
    354 => [
        'url' => 'https://treatwell.fr/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => '11490093c19dc659',
    ],
    355 => [
        'url' => 'https://treatwell.gr/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => 'e71d2c42fb86275b',
    ],
    356 => [
        'url' => 'https://treatwell.ie/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => 'bae964a08c1b5495',
    ],
    357 => [
        'url' => 'https://treatwell.it/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => 'a0dfa44eefda36a0',
    ],
    358 => [
        'url' => 'https://treatwell.lt/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => 'dfa5c11f2f4debd8',
    ],
    359 => [
        'url' => 'https://treatwell.lv/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => '931267e6e391e7b2',
    ],
    360 => [
        'url' => 'https://treatwell.nl/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => 'd9e4b09d897e157f',
    ],
    361 => [
        'url' => 'https://treatwell.pt/',
        'expect' => [
            'surface' => 'treatwell.book',
        ],
        'detector' => '60db16cba91b91ed',
    ],
    362 => [
        'url' => 'https://tripadvisor.com.au/Restaurant_Review-g1-d1-',
        'expect' => [
            'surface' => 'tripadvisor.listing',
            'identifier' => '1',
        ],
        'detector' => 'dd05626f17f5d3b0',
    ],
    363 => [
        'url' => 'https://tripadvisor.com/Restaurant_Review-g1-d1-',
        'expect' => [
            'surface' => 'tripadvisor.listing',
            'identifier' => '1',
        ],
        'detector' => '498d1ce6041c9aad',
    ],
    364 => [
        'url' => 'https://trustpilot.com/review/aaa.aa',
        'expect' => [
            'surface' => 'trustpilot.listing',
            'identifier' => 'aaa.aa',
        ],
        'detector' => '0edda8f51b17d39f',
    ],
    365 => [
        'url' => 'https://trybooking.com/',
        'expect' => [
            'surface' => 'trybooking.tickets',
        ],
        'detector' => '5532909197f3730e',
    ],
    366 => [
        'url' => 'https://tumblr.com/aaa',
        'expect' => [
            'surface' => 'tumblr.profile',
            'identifier' => 'aaa',
        ],
        'detector' => 'cf5d0ba6c3b3e13a',
    ],
    367 => [
        'url' => 'https://twitch.tv/aaa',
        'expect' => [
            'surface' => 'twitch.channel',
            'identifier' => 'aaa',
        ],
        'detector' => '08e97f225b18c135',
    ],
    368 => [
        'url' => 'https://twitter.com/a',
        'expect' => [
            'surface' => 'x.profile',
            'identifier' => 'a',
        ],
        'detector' => '43031574af12a099',
    ],
    369 => [
        'url' => 'https://ubereats.com/store/aaa/aaa',
        'expect' => [
            'surface' => 'uber_eats.order',
            'identifier' => 'aaa',
        ],
        'detector' => '354622fd7070cb07',
    ],
    370 => [
        'url' => 'https://upwork.com/freelancers/aa',
        'expect' => [
            'surface' => 'upwork.profile',
            'identifier' => 'aa',
        ],
        'detector' => '760f483c285beca4',
    ],
    371 => [
        'url' => 'https://vagaro.com/',
        'expect' => [
            'surface' => 'vagaro.book',
        ],
        'detector' => '51ca906a893af263',
    ],
    372 => [
        'url' => 'https://venmo.com/u/aaa',
        'expect' => [
            'surface' => 'venmo.profile',
            'identifier' => 'aaa',
        ],
        'detector' => '3b637d8bca677f64',
    ],
    373 => [
        'url' => 'https://venue.ink/',
        'expect' => [
            'surface' => 'venue_ink.book',
        ],
        'detector' => '010bea7a7d41534c',
    ],
    374 => [
        'url' => 'https://vimeo.com/aaa',
        'expect' => [
            'surface' => 'vimeo.account',
            'identifier' => 'aaa',
        ],
        'detector' => 'e7a3b337a1e70739',
    ],
    375 => [
        'url' => 'https://vimeo.com/channels/aaa',
        'expect' => [
            'surface' => 'vimeo.account',
            'identifier' => 'aaa',
        ],
        'detector' => '9fe8a0d71f1d37a9',
    ],
    376 => [
        'url' => 'https://vsco.co/aaa',
        'expect' => [
            'surface' => 'vsco.profile',
            'identifier' => 'aaa',
        ],
        'detector' => '34396e15d2c2c1dc',
    ],
    377 => [
        'url' => 'https://whatsapp.com/send',
        'expect' => [
            'surface' => 'whatsapp.chat',
        ],
        'detector' => 'aa4800576662c4e0',
    ],
    378 => [
        'url' => 'https://wixapps.net/bookings/',
        'expect' => [
            'surface' => 'wix_bookings.book',
        ],
        'detector' => '0206383166a62773',
    ],
    379 => [
        'url' => 'https://wolt.com/',
        'expect' => [
            'surface' => 'wolt.order',
        ],
        'detector' => 'f1da696a34a98b37',
    ],
    380 => [
        'url' => 'https://woocommerce.com/',
        'expect' => [
            'surface' => 'woocommerce.store',
        ],
        'detector' => '0bd78d1535c79d4e',
    ],
    381 => [
        'url' => 'https://x.com/a',
        'expect' => [
            'surface' => 'x.profile',
            'identifier' => 'a',
        ],
        'detector' => 'ba4979282ceaf778',
    ],
    382 => [
        'url' => 'https://yelp.com.au/biz/aaa',
        'expect' => [
            'surface' => 'yelp.listing',
            'identifier' => 'aaa',
        ],
        'detector' => '23b767116761378f',
    ],
    383 => [
        'url' => 'https://yelp.com/biz/aaa',
        'expect' => [
            'surface' => 'yelp.listing',
            'identifier' => 'aaa',
        ],
        'detector' => 'f404a3e56f0f9bf9',
    ],
    384 => [
        'url' => 'https://youtube.com/@aaa',
        'expect' => [
            'surface' => 'youtube.channel',
            'identifier' => 'aaa',
        ],
        'detector' => '131c12f7a0f5d323',
    ],
    385 => [
        'url' => 'https://youtube.com/c/aaa',
        'expect' => [
            'surface' => 'youtube.channel',
            'identifier' => 'aaa',
        ],
        'detector' => 'ed7d45efd0854383',
    ],
    386 => [
        'url' => 'https://youtube.com/channel/UCaaaaaaaaaaaaaaaaaaaaaa',
        'expect' => [
            'surface' => 'youtube.channel',
            'identifier' => 'UCaaaaaaaaaaaaaaaaaaaaaa',
        ],
        'detector' => '67c7aec08a3650d4',
    ],
    387 => [
        'url' => 'https://zenoti.com/',
        'expect' => [
            'surface' => 'zenoti.book',
        ],
        'detector' => 'ea00b095d01f2467',
    ],
    388 => [
        'url' => 'https://zomato.com/',
        'expect' => [
            'surface' => 'zomato.order',
        ],
        'detector' => '08ce3f9863cf55ac',
    ],
];
